spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BuildingCompany
    username: postgres
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
#  http:
#    converters:
#      preferred-json-mapper: gson

  main:
    allow-bean-definition-overriding: true

#logging:
#  level:
#    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
application-path: /api/v1