spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BuildingCompany
    username: postgres
    password: password
  mail:
    host: smtp.gmail.com
    port: 587
    username: cftteam.beta@gmail.com
    password: cft4ever
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  #  http:
  #    converters:
  #      preferred-json-mapper: gson

  main:
    allow-bean-definition-overriding: true

#logging:
#  level:
#    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
application:
  path: /api/v1
  default-page-size: 20

app:
  port: 8080
  domainName: localhost
  path: /api/v1

token:
  expiration: 2d

jwt:
  expiration: 3h
  secret: springTestKey